### ISSUE TITLE
Başarılı ödeme sonrası sorun

### ISSUE THREAD

**Issue by necoakdogan** [bsevgin/garantipos#11]
Merhabalar. Harika ve kolay bir entegrasyon hazırlamışsınız çok teşekkürler ancak ufak bir sorunum var. 3d ekranına yönlendirildikten sonra sms şifresi giriliyor ve success sayfasına gidiyor ancak ödeme gerçekleşmiyor? Sebebi nedir acaba? Yani ödeme yapılan karttaki tutarda eksilme olmuyor ve garanti pos panelinde de işlem yansımıyor.

**Comment by KadirHanKUZUCU** [comment]
merhabalar @necoakdogan aynı hatayı bende alıyorum acaba nasıl çözdünüz  ?
