### ISSUE TITLE
Post Sorunu 

### ISSUE THREAD

**Issue by leventguven** [bsevgin/garantipos#12]
Merhaba, Öncelikle böyle bir paylaşım için teşekkür ederim

example.php 31.satırda 'amount' => 1, olarak gönderdiğimde sorunsuz ödeme alıyor. Sorunum şöyle meydana geliyor index.php den post ettiğim                                     

 <input name="tutar" type="text" class="form-control" placeholder="Ödeme Tutarı Giriniz. " />

'amount' => $_POST["tutar"], post ettiğimde https://prnt.sc/IEonj4nO2Lb9 3d ekranına tutar doğru olarak geliyor fakat "error" ["message"]=> object(SimpleXMLElement)#7 (1) { [0]=> string(28) "Kullanıcı şifresi hatalı" } hatası geliyor banka destek birimi görüştüğümde https://prnt.sc/p7jWaeo4JKqf verilen yanıtlar https://prnt.sc/HmodPJwak6AF

amount alanına post değilde koddan rakam girdiğimde ödeme işlemi yapılıyor bu konuda destek olursanız çok sevinirim.

**Comment by bsevgin** [comment]
Merhaba,
Örnek işlemde tutarı 0,01 olarak değil de 1tl olarak yani 1tl çekim için 100 olarak gönderilmeli.
Açıklamada şu şekilde not düşmüştüm: "Çekilecek tutar (ondalıklı olarak değil tam sayı olarak gönderilmeli, örn. 12.34tl için 1234 gönderilmeli)".
Bunu teyit edip tekrar deneyebilir misiniz?

**Comment by leventguven** [comment]
Merhaba,

Amount => 1 olarak belirttiğimde sorunsuz olarak karttan 0,01 olarak çekim yapıyor bunda sorun yok dediğiniz gibi 1 tl yada 100tl yazsamda kabul etmiyor post ile geleni garantipos.php de bankanın belirttiği amount 0 olarak geldiği ama ben bankadan gelen mesajda tutar doğru yazıyor fakat işlem onaylanmıyor.

**Comment by bsevgin** [comment]
Tekrar merhaba,
ProvUser şifresini değiştirip yeni şifre ile deneyebilir misiniz?

**Comment by leventguven** [comment]
Merhaba,
Dediğiniz gibi değiştirdim fakat aynı sorun tekrar yaşanıyor bankaya amount 0 olarak gidiyor 

$amount=>$_POST["tutar"], kullandığımda bankaya 0 olarak gidiyor çalışmıyor
$amount=>100, kullandığımda kod kısmından 1 olarak ödeme sorunsuz bir şekilde gerçekleşiyor.

garantipos.php de değişkene atadığımda sorun oluşuyor sanırım siz post olarak işlem denemişmiydiniz

**Comment by halityilmaz1982** [comment]
ben işlem yaptığımda sürekli olarak beni belirttiğim errorurl adresine yönlendiriyor. bu hata mesajını nereden aldınız. debug modu da aktif ettim ama errorurl parametresine yönlendirildiğimden hataları göremiyorum.

**Comment by SafakB** [comment]
> Merhaba, Dediğiniz gibi değiştirdim fakat aynı sorun tekrar yaşanıyor bankaya amount 0 olarak gidiyor
> 
> $amount=>$_POST["tutar"], kullandığımda bankaya 0 olarak gidiyor çalışmıyor $amount=>100, kullandığımda kod kısmından 1 olarak ödeme sorunsuz bir şekilde gerçekleşiyor.
> 
> garantipos.php de değişkene atadığımda sorun oluşuyor sanırım siz post olarak işlem denemişmiydiniz

Gelen değeri string olarak alıyor ve 0 olarak gidiyor olabilir. Gelen değeri replace ederek nokta ve virgüllerden kurtulmalı, sonrası (int)  integer'a çevirmelisiniz. Bunu önceden kontrol ettirip 0 geldiğinde hata verdirmeniz gerekebilir.
