### ISSUE TITLE
Döviz Çekim 

### ISSUE THREAD

**Issue by KadirHanKUZUCU** [bsevgin/garantipos#13]
öncelikle paylaşım için teşekkürler ₺ olarak çekim sağlayabiliyorum ama yurtdışı kurları ile çekim yapmıyor çözebilen veya çekebilen var mı ?

**Comment by SafakB** [comment]
> öncelikle paylaşım için teşekkürler ₺ olarak çekim sağlayabiliyorum ama yurtdışı kurları ile çekim yapmıyor çözebilen veya çekebilen var mı ?

Döviz cinsinden işlem yapabildiğinizin onayını pos destek hattından kontrol etmenizi öneririm
