### ISSUE TITLE
Sınırlı sayıda ürün satarken bu kodu nasıl kullabiliriz?

### ISSUE THREAD

**Issue by nuriakman** [bsevgin/garantipos#2]
Merhaba,

Sınırlı sayıda ürün satarken (örneğin kalan son ürünü) aynı anda almak isteyen 2-3 kişi olursa bu kodu nasıl kullanabiliriz?

**Comment by bsevgin** [comment]
Merhaba,
Geç dönüşüm için kusura bakma. Soruna gelirsek;
`$result = $garantiPos->callback($action, $paymentType);`
Bu işlem sonucu başarılı ise ürünün stok sayısını 1 azaltırsın. Ayrıca sepet özelliğin de varsa bu ürünü sepetine ekleyenlerden ya silersin ya da açıklama ekleyip satın alamamalarını sağlarsın.
Aynı anda almaya çalışanları engellemek için ise;
`$garantiPos->pay($paymentType); //bankaya yönlendirme yapılıyor`
Bu işlemden önce stok kontrolü yapabilirsin.

Umarım yardımcı olabilmişimdir, kolay gelsin.

**Comment by bsevgin** [comment]
Bugfix veya extra bi istek olmadığından kapatıldı.
