### ISSUE TITLE
Bu projenin asp.net için olan kodları bulunurmu ? 

### ISSUE THREAD

**Issue by semt20** [bsevgin/garantipos#3]

**Comment by bsevgin** [comment]
Merhaba,
Geç dönüşüm için kusura bakma, yeni gördüm.
İlla bu şekilde kullanmak zorunda değilsin, Garanti Sanal Posun kendi dökümanındakileri uygulayarak da yapabilirsin. Orda .net için de örnek kodlar var.
Ama istersen şunu buldum belki işine yarayabilir:
https://github.com/c1982/GarantiVp

Kolay gelsin.
