### ISSUE TITLE
Minor bir öneri: Example da vardump yaparken

### ISSUE THREAD

**Issue by eyeniaras** [bsevgin/garantipos#5]
Hersey çok güzel olmuş eline sağlık. Aslında issue bile sayılmaz ama example.php de

```
echo '<pre>';
var_dump($result);
echo '</pre>';
```

yaparsan sonuc daha okunaklı yazılır.

**Comment by ibrahimsayar** [comment]
`function pre($val)
    {
        echo "<pre>";
        print_r($val);
        echo "</pre>";
    }`
`function prex($val)
    {
        echo "<pre>";
        print_r($val);
        echo "</pre>";
        exit;
    }`

Bu yazıları sürekli yazmamak için, bir fonksiyon kullanıyorum;
`prex($result);` dediğimde exit ile sayfayı da sonlandırıyor çıktıdan başka bir şey görünmüyor,
`pre($result)` dediğimde ise ilk çıktı sonra tüm sayfa yükleniyor belki işinize yarar.

**Comment by bsevgin** [comment]
Öneriniz için teşekkürler, ancak mümkün olduğunda basit tutmaya çalıştım. Bunun gibi eklemeler yapılabilir tabi forklayıp pull-request atarsanız memnuniyetle merge ederim. Tekrar teşekkürler. 👍
