### ISSUE TITLE
Ödeme Tipi Seçenekleri

### ISSUE THREAD

**Issue by nrtszr** [bsevgin/garantipos#7]
Kütüphane çok güzel olmuş ellerinize sağlık.
Ödeme tipleride eklenebilirse çok güzel olurmuş.

**Comment by bsevgin** [comment]
Teşekkürler, bu Garanti için olduğundan sadece 2 çeşit ödeme tipi var(Kredi kartı ile ödeme ve GarantiPay) ki parametreler arasında "paymentType" değeriyle kullanılabilir. Başka ödeme tipleri olacaksa başka sınıflara ihtiyacınız olacaktır.

**Comment by kaanakyuz** [comment]
Valla eline sağlık , çok güzel ve anlaşılır. Garantinin kendi verdiği dökümanlarda biraz kaybolmuştum , işimi gördü..

**Comment by bsevgin** [comment]
Teşekkürler, işinizi gördüğüne sevindim.

**Comment by nuriakman** [comment]
Elinize sağlık, çok güzel ve anlaşılır. Ben de Garantinin kendi verdiği dökümanlarda kaybolmuştum, işimi gördü :)
